export const COURS_LIST_REQUEST = 'COURS_LIST_REQUEST';
export const COURS_LIST_SUCCESS = 'COURS_LIST_SUCCESS';
export const COURS_LIST_FAIL = ' COURS_LIST_FAIL';

export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';
