export const ADD_COUPON_REQUEST = 'ADD_COUPON_REQUEST';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_FAIL = 'ADD_COUPON_FAIL';

export const COUPONS_LIST_REQUEST = 'COUPONS_LIST_REQUEST';
export const COUPONS_LIST_SUCCESS = 'COUPONS_LIST_SUCCESS';
export const COUPONS_LIST_FAIL = 'COUPONS_LIST_FAIL';

export const LIST_COACHS_RESPO_REQUEST = 'LIST_COACHS_RESPO_REQUEST';
export const LIST_COACHS_RESPO_SUCCESS = 'LIST_COACHS_RESPO_SUCCESS';
export const LIST_COACHS_RESPO_FAIL = 'LIST_COACHS_RESPO_FAIL';

export const ADD_SEANCE_REQUEST = 'ADD_SEANCE_REQUEST';
export const ADD_SEANCE_SUCCESS = 'ADD_SEANCE_SUCCESS';
export const ADD_SEANCE_FAIL = 'ADD_SEANCE_FAIL';
