export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const EMPLOYES_LIST_REQUEST = 'EMPLOYES_LIST_REQUEST';
export const EMPLOYES_LIST_SUCCESS = 'EMPLOYES_LIST_SUCCESS';
export const EMPLOYES_LIST_FAIL = 'EMPLOYES_LIST_FAIL';
export const EMPLOYES_LIST_RESET = 'EMPLOYES_LIST_RESET';

export const COACH_LIST_REQUEST = 'COACH_LIST_REQUEST';
export const COACH_LIST_SUCCESS = 'COACH_LIST_SUCCESS';
export const COACH_LIST_FAIL = 'COACH_LIST_FAIL';
export const COACH_LIST_RESET = 'COACH_LIST_RESET';

export const RESPONSABLE_LIST_REQUEST = 'RESPONSABLE_LIST_REQUEST';
export const RESPONSABLE_LIST_SUCCESS = 'RESPONSABLE_LIST_SUCCESS';
export const RESPONSABLE_LIST_FAIL = 'RESPONSABLE_LIST_FAIL';
export const RESPONSABLE_LIST_RESET = 'RESPONSABLE_LIST_RESET';

export const CLIENTS_LIST_REQUEST = 'CLIENTS_LIST_REQUEST';
export const CLIENTS_LIST_SUCCESS = 'CLIENTS_LIST_SUCCESS';
export const CLIENTS_LIST_FAIL = 'CLIENTS_LIST_FAIL';
export const CLIENTS_LIST_RESET = 'CLIENTS_LIST_RESET';

export const CLIENT_DELETE_REQUEST = 'CLIENT_DELETE_REQUEST';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';
export const CLIENT_DELETE_FAIL = ' CLIENT_DELETE_FAIL';

export const EMPLOYE_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const EMPLOYE_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const EMPLOYE_DELETE_FAIL = ' USER_DELETE_FAIL';

export const CLIENT_INFO_REQUEST = 'CLIENT_INFO_REQUEST';
export const CLIENT_INFO_SUCCESS = 'CLIENT_INFO_SUCCESS';
export const CLIENT_INFO_FAIL = 'CLIENT_INFO_FAIL';
export const CLIENT_INFO_RESET = 'CLIENT_INFO_RESET';

export const EMPLOYE_INFO_REQUEST = 'CLIENT_INFO_REQUEST';
export const EMPLOYE_INFO_SUCCESS = 'CLIENT_INFO_SUCCESS';
export const EMPLOYE_INFO_FAIL = 'CLIENT_INFO_FAIL';
export const EMPLOYE_INFO_RESET = 'CLIENT_INFO_RESET';

export const ADD_RESPONSABLE_REQUEST = 'ADD_RESPONSABLE_REQUEST';
export const ADD_RESPONSABLE_SUCCESS = 'ADD_RESPONSABLE_SUCCESS';
export const ADD_RESPONSABLE_FAIL = 'ADD_RESPONSABLE_FAIL';

export const ADD_COACH_REQUEST = 'ADD_COACH_REQUEST';
export const ADD_COACH_SUCCESS = 'ADD_COACH_SUCCESS';
export const ADD_COACH_FAIL = 'ADD_COACH_FAIL';

export const USER_CHANGE_ROLE_REQUEST = 'USER_CHANGE_ROLE_REQUEST';
export const USER_CHANGE_ROLE_SUCCESS = 'USER_CHANGE_ROLE_SUCCESS';
export const USER_CHANGE_ROLE_FAIL = 'USER_CHANGE_ROLE_FAIL';
export const USER_CHANGE_ROLE_RESET = 'USER_CHANGE_ROLE_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_FAIL';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';

export const GET_USER_IMAGE_REQUEST = 'GET_USER_IMAGE_REQUEST';
export const GET_USER_IMAGE_SUCCESS = 'GET_USER_IMAGE_SUCCESS';
export const GET_USER_IMAGE_FAIL = 'GET_USER_IMAGE_FAIL';
export const GET_USER_IMAGE_RESET = 'GET_USER_IMAGE_RESET';

export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';

export const DELETE_USER_IMAGE_REQUEST = 'DELETE_USER_IMAGE_REQUEST';
export const DELETE_USER_IMAGE_SUCCESS = 'DELETE_USER_IMAGE_SUCCESS';
export const DELETE_USER_IMAGE_FAIL = 'DELETE_USER_IMAGE_FAIL';
export const DELETE_USER_IMAGE_RESET = 'DELETE_USER_IMAGE_RESET';

export const GET_LOG_REQUEST = 'GET_LOG_REQUEST';
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS';
export const GET_LOG_FAIL = 'GET_LOG_FAIL';
export const GET_LOG_RESET = 'GET_LOG_RESET';

export const ADD_ABONNEMENT_REQUEST = 'ADD_ABONNEMENT_REQUEST';
export const ADD_ABONNEMENT_SUCCESS = 'ADD_ABONNEMENT_SUCCESS';
export const ADD_ABONNEMENT_FAIL = 'ADD_ABONNEMENT_FAIL';

export const SERVICES_LIST_REQUEST = 'SERVICES_LIST_REQUEST';
export const SERVICES_LIST_SUCCESS = 'SERVICES_LIST_SUCCESS';
export const SERVICES_LIST_FAIL = 'SERVICES_LIST_FAIL';

export const SERVICES_DETAIL_REQUEST = 'SERVICES_DETAIL_REQUEST';
export const SERVICES_DETAIL_SUCCESS = 'SERVICES_DETAIL_SUCCESS';
export const SERVICES_DETAIL_FAIL = 'SERVICES_DETAIL_FAIL';

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';
export const CREATE_CART_RESET = 'CREATE_CART_RESET';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
